version: "3"  
services:
  http_response_checks:
    image: rickjury/sumo-telegraf-agent
    container_name: http_check_sumologic1
    hostname: http_check_sumologic1
    command: [ "telegraf","--config","http_response.conf"]
    environment:
      SUMO_URL: "${SUMO_URL}"
      env: "test"
      location: "mymac-compose"
      service: demo_dc
      urls: http://sumologic.com,https://help.sumologic.com
  ping_checks:
    image: rickjury/sumo-telegraf-agent
    container_name: ping_check1
    hostname: ping_check1
    command: [ "telegraf","--config","ping.conf"]
    environment:
      SUMO_URL: "${SUMO_URL}"
      env: "test"
      location: mymac-compose
      service: demo_dc
      urls: sumologic.com
  statsd_listener:
    image: rickjury/sumo-telegraf-agent
    container_name: statsd
    hostname: statsd
    command: [ "telegraf","--config","statsd.conf"]
    environment:
      SUMO_URL: "${SUMO_URL}"
      env: "test"
      location: mymac-compose
      service: demo_dc
      urls: sumologic.com
      interval: 15s
      flush_interval: 15s
    ports:
      - 8125:8125/udp